### ISSUE TITLE
Do not scape expressions

### ISSUE THREAD

**Issue by blikblum** [atomictag/incremental-bars#4]
Since the incremental-dom creates the elements through the DOM api instead of setting `innerHTML` or equivalent, like is done with string templates, is not necessary to escape the expressions.

This has some advantages:

For expressions with HTML characters the rendering output will the same as the one using string templates. 
Example:

```
var data = {value: '<my-element>'}
el.innerHTML = Handlebars.compile('{{value}}')(data)
```

renders &lt;my-element&gt;

```
var data = {value: '<my-element>'}
// pseudo code
IncrementalBars.compile('{{value}}')(data)
```

currently renders \&lt;my-element\&gt;  . By removing the escaping the rendered output will be the same as with html backend

Also important compiled templates will be smaller and will execute faster

**Comment by atomictag** [comment]
That's a fair point. However, I think this can be easily done by passing `noEscape` as an option to Handlebars (as documented [here](http://handlebarsjs.com/reference.html) - and demo'd in this [RunKit](https://runkit.com/593aa1f1727bdc0012e02621/593aa1f1727bdc0012e02622)).

Otherwise we could force this in the [compiler override](https://github.com/atomictag/incremental-bars/blob/master/src/handlebars/instrumented-compiler.js#L45), e.g.:

    // OVERRIDE: appendEscaped    
    JavaScriptCompilerInstrumented.prototype.appendEscaped = function appendEscaped_instrumented() {
        if(this.options.backend != null && this.options.backend !== DEFAULT_BACKEND) {
            this.pushSource(this.appendToBuffer([ this.popStack() ]));            
        } else {
            JavaScriptCompilerDefault.prototype.appendEscaped.call(this);
        }
    }

Personally I prefer not to add things that can be done with plain Handlebars - but you have a valid point that perhaps it's not so obvious to most users.

**Comment by atomictag** [comment]
There you go. Version 1.0.6 - which always prevents escaping - is now on npm.

**Comment by blikblum** [comment]
Many thanks.
